### ISSUE TITLE
Feat: 회원 파트 프론트에  연결하기

### ISSUE THREAD

**Issue by lala9663** [Metanet-Team3/final-repo#36]
## 📑 Description

백엔드로 만든 기능들 view단에 하나씩 연결하기

## ✅ Tasks

- [x] 회원가입
- [x] 로그인
- [x] 로그인 후 토큰 값 sessionStroage에 저장하기
- [x] 저장한걸 autrhorzation이름으로 헤더에 넣기
- [x] 넣은 후 그걸로 정보 조회하기

## 👨‍💻️️ References

처음하는 부분이라 시간 진짜 오래걸리네,,,,
